packages:
  - npm
  - napi
  - fixtures/pnpm
  - fixtures/tsconfck
  - fixtures/pnpm/pnpm-workspace/**

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.2.0

ignoreScripts: true

minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"

ignoredBuiltDependencies:
  - esbuild

overrides:
  vite: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"

virtualStoreDirMaxLength: 1024
