packages:
  - npm
  - napi
  - fixtures/pnpm
  - fixtures/tsconfck
  - fixtures/pnpm/pnpm-workspace/**

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.11
  vitest: npm:@voidzero-dev/vite-plus-test@latest

ignoreScripts: true

ignoredBuiltDependencies:
  - esbuild

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"

virtualStoreDirMaxLength: 1024
