name: Pnpm

description: Install pnpm

inputs:
  architecture:
    description: The architecture to use
    required: false

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        node-version-file: .node-version
        architecture: ${{ inputs.architecture }}
        cache: pnpm

    - if: ${{ inputs.architecture == 'x86' }}
      shell: bash
      run: pnpm config set supportedArchitectures.cpu "ia32"

    - name: pnpm
      shell: bash
      run: |
        corepack enable
        pnpm install

    - name: yarn
      shell: bash
      run: |
        cd fixtures/pnp
        corepack enable
        yarn install
