name: Pnpm

description: Install pnpm

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: pnpm

    - name: Enable corepack
      if: ${{ inputs.node-version != '16' }}
      shell: bash
      run: |
        if [[ "${{runner.os}}" == "Windows" ]]; then
          # add the npm prefix to PATH to ensure the installed corepack work properly
          NPM_PREFIX=$(cygpath -u "$(npm config get prefix)")
          export PATH="$NPM_PREFIX:$PATH"
        fi
        npm install -g corepack@0.31.0 --force
        echo "Corepack version: $(corepack --version)"
        corepack enable

    - name: yarn
      shell: bash
      run: |
        cd fixtures/pnp
        yarn install

    - name: pnpm
      shell: bash
      run: |
        pnpm install
