name: Pnpm

description: Install pnpm

runs:
  using: composite
  steps:
    - uses: oxc-project/setup-node@f42e3bda950c7454575e78ee4eaac880a077700c # v1.0.0

    - name: yarn
      shell: bash
      run: |
        cd fixtures/pnp
        corepack enable
        yarn install

        cd ../global-pnp
        yarn install
