name: Pnpm

description: Install pnpm

inputs:
  architecture:
    description: The architecture to use
    required: false
  cpu:
    description: The cpu architecture to use
    required: false

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version-file: .node-version
        architecture: ${{ inputs.architecture }}
        cache: pnpm

    - if: ${{ inputs.cpu }}
      shell: bash
      run: node -e 'console.log(`\nsupportedArchitectures:\n  cpu:\n    - ${process.env.CPU_ARCH}`)' >> pnpm-workspace.yaml
      env:
        CPU_ARCH: ${{ inputs.cpu }}

    - name: pnpm
      shell: bash
      run: |
        corepack enable
        pnpm install

    - name: yarn pnp
      shell: bash
      run: |
        cd fixtures/pnp
        yarn install

        cd ../global-pnp
        yarn install

        cd ../yarn
        yarn install
