name: Setup Node and pnpm

description: Setup Node.js and pnpm with caching, and install yarn fixtures

inputs:
  architecture:
    required: false
    description: "Optional architecture for Node.js (e.g., x64, arm64). If not specified, defaults to the runner architecture."

  cpu:
    required: false
    description: "Optional CPU architecture for pnpm supportedArchitectures configuration (e.g., x64, arm64)."

runs:
  using: composite
  steps:
    - uses: oxc-project/setup-node@ab97f03642370d79a7e96dd286bd02a1be40e0ba # v1.3.0
      with:
        architecture: ${{ inputs.architecture }}
        cpu: ${{ inputs.cpu }}

    - name: Install yarn fixtures
      shell: bash
      run: |
        corepack enable
        cd fixtures/pnp
        yarn install

        cd global-pnp
        yarn install

        cd ../../yarn
        yarn install
