name: Benchmark

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for OIDC authentication with CodSpeed
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2

      - uses: oxc-project/setup-rust@3d6fb132fbe7cdcb66bf8ec193911c2945369d12 # v1.0.17
        with:
          cache-key: benchmark
          save-cache: ${{ github.ref_name == 'main' }}
          tools: cargo-codspeed,just

      - uses: ./.github/actions/pnpm

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: 1.3.14

      - name: Install bench-pm fixtures
        run: just install-bench-fixtures

      - run: cargo codspeed build --features codspeed,yarn_pnp
        env:
          RUSTFLAGS: "-C debuginfo=1 -C strip=none"

      - uses: CodSpeedHQ/action@63f3e98b61959fe67f146a3ff022e4136fe9bb9c # v4.17.6
        timeout-minutes: 30
        with:
          mode: simulation
          run: cargo codspeed run
