name: Cargo Deny

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "Cargo.lock"
      - "deny.toml"
      - ".github/workflows/deny.yml"
  push:
    branches:
      - main
    paths:
      - "Cargo.lock"
      - "deny.toml"
      - ".github/workflows/deny.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/checkout-action@v1

      - uses: oxc-project/setup-rust@v1.0.0
        with:
          restore-cache: false
          tools: cargo-deny

      - run: cargo deny check
